class Data:
    BLACK_BUN = "black bun"
    WHITE_BUN = 'white bun'
    RED_BUN = 'red bun'
    BLACK_BUN_PRICE = 100
    WHITE_BUN_PRICE = 200
    RED_BUN_PRICE = 300
    HOT_SAUCE = "hot sauce"
    SOUR_CREAM = "sour cream"
    CHILLI_SAUCE = "chili sauce"
    HOT_SAUCE_PRICE = 100
    SOUR_CREAM_PRICE = 200
    CHILLI_SAUCE_PRICE = 300
    CUTLET = 'cutlet'
    DINOSAUR = 'dinosaur'
    SAUSAGE = 'sausage'
    CUTLET_PRICE = 100
    DINOSAUR_PRICE = 200
    SAUSAGE_PRICE = 300